title: Project Chimera
description: An FF6-inspired JRPG where reality is not what it seems
baseurl: "/project-chimera"
url: "https://colorpulse6.github.io"

# Build
markdown: kramdown
permalink: /devlog/:year/:month/:day/:title/

# Theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# Collections
collections:
  characters:
    output: true
    permalink: /characters/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
